spring:
  jpa:
    open-in-view: false
  mvc:
    converters:
      preferred-json-mapper: gson
  config:
    import: optional:file:.env[.properties]
  datasource:
    driverClassName: org.sqlite.JDBC
    password: ${DB_PASSWORD:password}
    url: ${DB_URL:url}
    username: ${DB_USERNAME:username}
management:
  endpoint:
    metrics:
      enabled: true
  metrics:
    tags:
      application: "prototype"
  datadog:
    metrics:
      export:
        api-key: ${DATADOG_API_KEY}
        enabled: true
        step: 10s
        uri: "https://api.us5.datadoghq.com"

logging:
  level:
    root: info