spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    driverClassName: org.sqlite.JDBC
    password: ${DB_PASSWORD:password}
    url: ${DB_URL:url}
    username: ${DB_USERNAME:username}